dns-latency:
  schedule: "H/5 * * * *"
  param:
    destinations:
      - www.amazon.com
      - chicago.suntimes.com
      - www.chicagotribune.com
      - cs.uchicago.edu
      - www.facebook.com
      - www.google.com
      - www.wikipedia.org
      - www.youtube.com
      - www.nytimes.com

hops:
  command: hops-traceroute
  schedule: "H/5 * * * *"
  unless: &scamper-on |
    env.NETRICS_BETA_SCAMPER | default('0') | int == 1
  param:
    destinations:
      www.google.com: google

hops-scamper:
  schedule: "H/5 * * * *"
  if: *scamper-on

ip:
  schedule: "H/5 * * * *"
  unless: env.NETRICS_IP_QUERY | default('1') | int == 0

lml:
  command: lml-traceroute
  schedule: "H/5 * * * *"
  unless: *scamper-on
  param:
    destinations:
      1.1.1.1: Cloudflare_DNS

lml-scamper:
  schedule: "H/5 * * * *"
  if: *scamper-on

ping:
  schedule: "H/5 * * * *"
  param:
    destinations:
      # network locator: results label
      www.google.com: google
      www.amazon.com: amazon
      www.wikipedia.org: wikipedia
      www.youtube.com: youtube
      www.facebook.com: facebook
      www.chicagotribune.com: tribune
      chicago.suntimes.com: suntimes
      cs.uchicago.edu: uchicago
      4.71.251.129: Chicago
      4.35.238.193: Washington_DC
      4.71.254.129: Atlanta
      4.34.58.1: Denver
      38.102.0.65: Seattle
      183.178.65.1: Hong_Kong
      175.45.79.73: Sydney
      196.24.45.129: Johannesburg
      41.231.21.1: Tunis
      77.67.119.129: Paris
      195.89.146.193: Stockholm
      190.98.158.1: Sao_Paulo

speed-ookla:
  #
  # schedule: hourly
  #
  # hashed version: with the above name: every hour on the 49th minute
  #
  # schedule: "H * * * *"
  #
  # static version: every hour on the 0th minute
  #
  # (used in place of hash-based offset for all speed tests to try to ensure
  # that they test similar conditions. speed tests will NOT collide with any
  # others thanks to "tenancy" below.)
  #
  schedule: "*/5 * * * *"

  #
  # scheduling (scheduler)
  #
  # disallow concurrent measurements
  #
  scheduling:
    tenancy: 1

  param:
    accept_license: true
    timeout: 80
